### PR TITLE
Added events for filtered menu and fixed misspelled event name

### PR DESCRIPTION
**Pull request by samjcapiznon**

### CODE REVIEW

**Comment by jch254** [comment]
Thanks @samjcapiznon!

**Review by johnatdoshii — DISMISSED** [review]
Hey @samjcapiznon, thanks for adding these.

Unfortunately, I just realised that there are some other events missing, so I'll need to look at adding those:

- `location_subscription`
- `location_hours_updated`
- `loyalty_checkin_created`
- `loyalty_checkin_updated`
- `loyalty_checkin_deleted`

If you wish to add them in to this PR then great, otherwise we can look to add them in a subsequent PR. 🙇‍♂️

**Comment by samjcapiznon** [comment]
> Hey @samjcapiznon, thanks for adding these.
> 
> Unfortunately, I just realised that there are some other events missing, so I'll need to look at adding those:
> 
> * `location_subscription`
> * `location_hours_updated`
> * `loyalty_checkin_created`
> * `loyalty_checkin_updated`
> * `loyalty_checkin_deleted`
> 
> If you wish to add them in to this PR then great, otherwise we can look to add them in a subsequent PR. 🙇‍♂️

No worries, I've added them on my PR.

**Review by johnatdoshii — APPROVED** [review]
Amazing - thanks for that 🚀

**Review by johnatdoshii — APPROVED** [review]

**Pull request merged**
