### PR TITLE
INT 175 : Make get functions private and update version to 5.0.0

### PR DESCRIPTION
**Pull request by muhammadatdoshii**
[INT 175](https://doshii.atlassian.net/browse/INT-175)

### CODE REVIEW

**Review by johnatdoshii — APPROVED** [review]

**Comment by johnatdoshii** [comment]
Can we hold off on merging until @carlosatdoshii has also reviewed, to check to make sure the proposed changes would not create any issues for Smart Hospo? - it should be fine, but good to check. 🙇

**Comment by muhammadatdoshii** [comment]
> Can we hold off on merging until @carlosatdoshii has also reviewed, to check to make sure the proposed changes would not create any issues for Smart Hospo? - it should be fine, but good to check. 🙇

Totally agree. Glad you pushed in a message before I merged. Thanks

**Review by carlosatdoshii — APPROVED** [review]
Looks good to me 👍. Great work on this one @muhammadatdoshii

**Comment by muhammadatdoshii** [comment]
> Looks good to me 👍. Great work on this one @muhammadatdoshii

Thanks so much @carlosatdoshii ! 🙇

**Pull request merged**
